In [ ]:
Share. os.listdir('/content/drive/MyDrive')

['PXL_20250627_042827648.mp4',
 '04 Financial Well-Being Meditation.mp3',
 '05 Mystical Intuition (Epsilon White Noise).m4a',
 '11 741 Hz Awakening Intuition.m4a',
 '01 Ecstatic State of Consciousness (Epsilon White Noise).m4a',
 '06 Spirtitual Rejuvenation (Epsilon White Noise).m4a',
 '07 396 Hz Liberating Guilt and Fear.m4a',
 '04 Out of Body (Epsilon White Noise).m4a',
 '09 528 Hz Transformation and Miracles (DNA Repair).m4a',
 '10 639 Hz Connecting_relationships.m4a',
 '02 Anti-Aging (Epsilon White Noise).m4a',
 '08 417 Hz Undoing Situations and Facilitating Change.m4a',
 '03 Suspended Animation (Epsilon Binaural Beats & White Noise).m4a',
 '12 852 Hz Returning To Spiritual Order.m4a',
 'message.html',
 'C.V  UPDATED.doc.gdoc',
 'Download',
 'Android',
 'DCIM',
 'Videoshop',
 'Tencent',
 'WhatsApp',
 'JUAN DAVID AMAYA  Declaración de Cambio No. 4 VB (1).XLS',
 'JUAN DAVID AMAYA  Declaración de Cambio No. 4 VB.XLS.gsheet',
 'JUAN DAVID AMAYA  Declaración de Cambio No. 4 VB.gsheet',
 'JUAN DAVID AMAYA  Declaración de Cambio No. 4 VB.XLS',
 '377.m4a',
 'F31.m4a',
 'F32.m4a',
 'Untitled document (8).gdoc',
 'Untitled document (7).gdoc',
 'Doc - Sep 16 2020 - 4-15 PM.pdf',
 'THERE IS NO CRYING IN TRUMP REMOVAL.gdoc',
 'Healthcare .gdoc',
 'Words for MAGA.gdoc',
 'Pulled over .gdoc',
 'Bumble .gdoc',
 'JUAN JUAN.rtf.gdoc',
 'Day 13 - RTT Session for Abundance Mindset- Rewiring.mp3',
 'Untitled document (6).gdoc',
 'Untitled document (5).gdoc',
 'Copy of 2021 Intermediate Program Nutrition Spreadsheet (With Workout Tracker) .gsheet',
 'Dares.gdoc',
 'BWS Intermediate - Workouts.pdf',
 'Untitled document (4).gdoc',
 'Untitled document (3).gdoc',
 'Untitled spreadsheet (6).gsheet',
 'DATA DATA DATA ',
 'Monthly Sales (1).gsheet',
 'Spreadsheet Errors and Fixes Demo Sheets (1).gsheet',
 'Monthly Sales - Functions 101 (1).gsheet',
 '2019 Data Analyst Jobs.gsheet',
 'Scope-Of-Work Template.gdoc',
 'Learning Log Template: Define problems and ask questions with data.gdoc',
 'On the Rise forecast report.gsheet',
 'Example Spreadsheet - Entertainment Expenses  (1).gsheet',
 'Course 3 Week 1 Glossary | DA terms and definitions.gdoc',
 'Feed.gdoc',
 'Untitled document (2).gdoc',
 'Untitled spreadsheet.xlsx',
 'Untitled spreadsheet (5).gsheet',
 'Sales Rep Cities, States, and Parts (2).gsheet',
 'Untitled spreadsheet (4).gsheet',
 'CODEC JUAN (1) (1).xlsx',
 'Student Perfomance Data.gsheet',
 'Sales Rep Cities, States, and Parts (1).gsheet',
 'Student Performace Data.gsheet',
 'Intro to BigQuery solutions (1).gdoc',
 'Untitled document (1).gdoc',
 'Per diem Tucson .gdoc',
 'Population, Latin and Caribbean Countries, 2010-2019.gsheet',
 'Monthly Sales.gsheet',
 'Spreadsheet Errors and Fixes Demo Sheets.gsheet',
 'Monthly Sales - Functions 101.gsheet',
 'CustomerSurvey (2).gsheet',
 'CustomerSurvey (1).gsheet',
 'CustomerSurvey.gsheet',
 'HistoricalSales.gsheet',
 'Untitled spreadsheet (3).gsheet',
 'Sales Rep Cities, States, and Parts.gsheet',
 'COLEGIOS.gsheet',
 'Learning Log Template: Review file structure and naming conventions.gdoc',
 'CustomerSurveyData.gsheet',
 'DeliveryTimes DistanceData.gsheet',
 'Sample Size Calculator (1).gsheet',
 'Margin of Error Calculator.gsheet',
 'June 2014 Invoices (1).gsheet',
 'International Logistics Association Memberships - Data to Merge.gsheet',
 'Global Logistics Association - Data to Merge.gsheet',
 'Data Spreadsheet for "Cleaning with Spreadsheets"  (4).gsheet',
 'International Logistics Association Memberships - Data for Cleaning (1).gsheet',
 'Cosmetics Inc. - Data for Cleaning.gsheet',
 'Cosmetics Inc. - Data for Pivot Table and VLOOKUP.gsheet',
 'whatsapp_20221101-233835_Chismiaus 😍.amr',
 'whatsapp_20221101-235047_Chismiaus 😍.amr',
 'sf_boba_tea_shop_data.gsheet',
 'Learning Log Template: Develop your approach to cleaning data.gdoc',
 'Untitled document.docx',
 'Fidu.gdoc',
 'CODEC.gsheet',
 "Jeff's Party Planet - Data for Cleaning (1).gsheet",
 'Kitty Survey Feedback (1).gsheet',
 'CODEC JUAN (1).xlsx',
 'Example Spreadsheet - Entertainment Expenses .gsheet',
 'AMAZON STEPS.gdoc',
 'juan_david_amaya_ossa_formulación.pdf',
 'Untitled spreadsheet (2).gsheet',
 'Studen Performance Data.gsheet',
 'Intro to BigQuery solutions.gdoc',
 'Sample Size Calculator.gsheet',
 'Copy of Built With Science Intermediate Program Nutrition Spreadsheet (With Workout Tracker)  (4).gsheet',
 'Copy of Built With Science Intermediate Program Nutrition Spreadsheet (With Workout Tracker)  (3).gsheet',
 'Copy of Built With Science Intermediate Program Nutrition Spreadsheet (With Workout Tracker)  (2).gsheet',
 'Copy of Built With Science Intermediate Program Nutrition Spreadsheet (With Workout Tracker)  (1).gsheet',
 'Copy of Built With Science Intermediate Program Nutrition Spreadsheet (With Workout Tracker) .gsheet',
 'June 2014 Invoices.gsheet',
 'Data Spreadsheet for "Cleaning with Spreadsheets"  (3).gsheet',
 'Data Spreadsheet for "Cleaning with Spreadsheets"  (2).gsheet',
 'Data Spreadsheet for "Cleaning with Spreadsheets"  (1).gsheet',
 'Data Spreadsheet for "Cleaning with Spreadsheets" .gsheet',
 'International Logistics Association Memberships - Data for Cleaning.gsheet',
 'SF_Datos_Tiendas_Te_Burbujas.gsheet',
 'Untitled spreadsheet (1).gsheet',
 'Apoyo a Uribe ?.gdoc',
 "Jeff's Party Planet - Data for Cleaning.gsheet",
 'Resume Template 1.gdoc',
 'Resume Template 2.gdoc',
 'Kitty Survey Feedback.gsheet',
 'Movie Data Starter Project (2).gsheet',
 'Party Plan Spreadsheet.gsheet',
 'Dataset for Project:  CONCAT function.gsheet',
 'Learning-Log-Template_Start-a-data-analysis-checklist.gdoc',
 'VLOOKUP Practice Sheet (2).gsheet',
 'VLOOKUP Practice Sheet (1).gsheet',
 'VLOOKUP Practice Sheet.gsheet',
 'Discount-Variety-Store-433-Monthly-Sales.gsheet',
 'Kitchen Supplies, Transactions.gsheet',
 'Working with Conditions.gsheet',
 'Copy of Cosmetics Inc. (1).gsheet',
 'Copy of Cosmetics Inc..gsheet',
 'Movie Data Starter Project (1).gsheet',
 'Movie Data Starter Project.gsheet',
 'Inventory.csv',
 'Sales.csv',
 'Products.csv',
 'Untitled spreadsheet.gsheet',
 'bq-results-20231209-230425-1702164176706',
 'Tu guía intermedia para SQL_SPA.gdoc',
 'Dynamic Dataset.gsheet',
 'The formula',
 'Making your own visualization - example dataset.gsheet',
 'CO2-Dataset.xlsx',
 'Copy of Customer service survey responses.gsheet',
 'Customer-service-survey-responses (1).gsheet',
 'Customer-service-survey-responses.gsheet',
 'Cosmetics Inc. (1).gsheet',
 'Cosmetics Inc..gsheet',
 'CO2 Dataset (3).gsheet',
 'CO2 Dataset (2).gsheet',
 'CO2 Dataset (1).gsheet',
 'CO2 Dataset.gsheet',
 'WhatsApp Chat with Ana Beatriz Vianna (2).gdoc',
 'Reference guide: Functions.gdoc',
 'Reference guide: Python operators.gdoc',
 'WhatsApp Chat with Ana Beatriz Vianna (1).gdoc',
 'WhatsApp Chat with Ana Beatriz Vianna.gdoc',
 'Untitled document.gdoc',
 'Garotas.gdoc',
 'Reference guide: Dictionaries.gdoc',
 'Colab Notebooks']

In [ ]:
os.listdir('/content/drive/MyDrive/Colab Notebooks')

['202512-divvy-tripdata.xlsx',
 '202511-divvy-tripdata.xlsx',
 '202509-divvy-tripdata.xlsx',
 '202510-divvy-tripdata.xlsx',
 '202606-divvy-tripdata.xlsx',
 '202605-divvy-tripdata.xlsx',
 '202602-divvy-tripdata.xlsx',
 '202604-divvy-tripdata.xlsx',
 '202603-divvy-tripdata.xlsx',
 '202601-divvy-tripdata.xlsx',
 '202508-divvy-tripdata.xlsx',
 'cyclistic_consolidado_limpio.csv',
 '202607-divvy-tripdata.xlsx',
 'Untitled0.ipynb']

In [ ]:
os.listdir('/content/drive/MyDrive/Colab Notebooks')

['202512-divvy-tripdata.xlsx',
 '202511-divvy-tripdata.xlsx',
 '202509-divvy-tripdata.xlsx',
 '202510-divvy-tripdata.xlsx',
 '202606-divvy-tripdata.xlsx',
 '202605-divvy-tripdata.xlsx',
 '202602-divvy-tripdata.xlsx',
 '202604-divvy-tripdata.xlsx',
 '202603-divvy-tripdata.xlsx',
 '202601-divvy-tripdata.xlsx',
 '202508-divvy-tripdata.xlsx',
 'cyclistic_consolidado_limpio.csv',
 '202607-divvy-tripdata.xlsx',
 'Untitled0.ipynb']

In [ ]:
os.listdir('/content/drive/MyDrive/Colab Notebooks')

['202512-divvy-tripdata.xlsx',
 '202511-divvy-tripdata.xlsx',
 '202509-divvy-tripdata.xlsx',
 '202510-divvy-tripdata.xlsx',
 '202606-divvy-tripdata.xlsx',
 '202605-divvy-tripdata.xlsx',
 '202602-divvy-tripdata.xlsx',
 '202604-divvy-tripdata.xlsx',
 '202603-divvy-tripdata.xlsx',
 '202601-divvy-tripdata.xlsx',
 '202508-divvy-tripdata.xlsx',
 'cyclistic_consolidado_limpio.csv',
 '202607-divvy-tripdata.xlsx',
 'Untitled0.ipynb']

In [ ]:
import pandas as pd

agosto = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/202508-divvy-tripdata.xlsx')
agosto.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_lenght,day_of_teh_week
0,5C00A6B5A60E4AFC,electric_bike,2025-08-28 15:56:46.803,2025-08-28 16:11:54.890,NaN,NaN,NaN,NaN,41.88,-87.64,41.89,-87.62,casual,0 days 00:15:08.087000,5
1,FB25D4B923656D01,electric_bike,2025-08-27 19:15:53.059,2025-08-27 19:34:13.683,NaN,NaN,NaN,NaN,41.95,-87.64,41.89,-87.61,casual,0 days 00:18:20.624000,4
2,C665B0EC937C860C,electric_bike,2025-08-27 20:27:31.394,2025-08-27 20:38:29.890,NaN,NaN,NaN,NaN,41.92,-87.65,41.90,-87.64,casual,0 days 00:10:58.496000,4
3,C68C54D5FD9717C2,electric_bike,2025-08-28 15:33:21.055,2025-08-28 15:39:58.052,NaN,NaN,NaN,NaN,41.89,-87.65,41.88,-87.65,casual,0 days 00:06:36.997000,5
4,902D69C29B0E65F8,electric_bike,2025-08-28 09:59:44.846,2025-08-28 10:11:17.343,NaN,NaN,NaN,NaN,41.98,-87.68,41.95,-87.70,casual,0 days 00:11:32.497000,5

In [ ]:
import pandas as pd

agosto = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/202508-divvy-tripdata.xlsx')
agosto.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_lenght,day_of_teh_week
0,5C00A6B5A60E4AFC,electric_bike,2025-08-28 15:56:46.803,2025-08-28 16:11:54.890,NaN,NaN,NaN,NaN,41.88,-87.64,41.89,-87.62,casual,0 days 00:15:08.087000,5
1,FB25D4B923656D01,electric_bike,2025-08-27 19:15:53.059,2025-08-27 19:34:13.683,NaN,NaN,NaN,NaN,41.95,-87.64,41.89,-87.61,casual,0 days 00:18:20.624000,4
2,C665B0EC937C860C,electric_bike,2025-08-27 20:27:31.394,2025-08-27 20:38:29.890,NaN,NaN,NaN,NaN,41.92,-87.65,41.90,-87.64,casual,0 days 00:10:58.496000,4
3,C68C54D5FD9717C2,electric_bike,2025-08-28 15:33:21.055,2025-08-28 15:39:58.052,NaN,NaN,NaN,NaN,41.89,-87.65,41.88,-87.65,casual,0 days 00:06:36.997000,5
4,902D69C29B0E65F8,electric_bike,2025-08-28 09:59:44.846,2025-08-28 10:11:17.343,NaN,NaN,NaN,NaN,41.98,-87.68,41.95,-87.70,casual,0 days 00:11:32.497000,5

In [ ]:
 .

In [ ]:

archivos = ['202508-divvy-tripdata.xlsx', '202509-divvy-tripdata.xlsx', '202510-divvy-tripdata.xlsx',
            '202511-divvy-tripdata.xlsx', '202512-divvy-tripdata.xlsx', '202601-divvy-tripdata.xlsx',
            '202602-divvy-tripdata.xlsx', '202603-divvy-tripdata.xlsx', '202604-divvy-tripdata.xlsx',
            '202605-divvy-tripdata.xlsx', '202606-divvy-tripdata.xlsx', '202607-divvy-tripdata.xlsx']

In [ ]:
datos_completos.shape

(5877002, 21)

In [ ]:
!pip install python-calamine --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 919.5/919.5 kB 35.5 MB/s eta 0:00:00

In [ ]:
ruta = '/content/drive/MyDrive/Colab Notebooks/'
tablas = []

for archivo in archivos:
    print(f"Leyendo {archivo}...")
    tabla = pd.read_excel(ruta + archivo, engine='calamine')
    print(f"  → {tabla.shape[0]} filas cargadas")
    tablas.append(tabla)

datos_completos = pd.concat(tablas, ignore_index=True)
print("Listo:", datos_completos.shape)

Leyendo 202508-divvy-tripdata.xlsx...
  → 790177 filas cargadas
Leyendo 202509-divvy-tripdata.xlsx...
  → 714759 filas cargadas
Leyendo 202510-divvy-tripdata.xlsx...
  → 646039 filas cargadas
Leyendo 202511-divvy-tripdata.xlsx...
  → 356628 filas cargadas
Leyendo 202512-divvy-tripdata.xlsx...
  → 140534 filas cargadas
Leyendo 202601-divvy-tripdata.xlsx...
  → 137787 filas cargadas
Leyendo 202602-divvy-tripdata.xlsx...
  → 201450 filas cargadas
Leyendo 202603-divvy-tripdata.xlsx...
  → 317037 filas cargadas
Leyendo 202604-divvy-tripdata.xlsx...
  → 448252 filas cargadas
Leyendo 202605-divvy-tripdata.xlsx...
  → 653704 filas cargadas
Leyendo 202606-divvy-tripdata.xlsx...
  → 762550 filas cargadas
Leyendo 202607-divvy-tripdata.xlsx...
  → 869051 filas cargadas
Listo: (6037968, 19)

In [ ]:
datos_completos.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'ride_lenght', 'day_of_teh_week', 'ride_leght',
       'day_of_the_week', 'day_of_weel', 'day_of_week', 'ride_length',
       'ride_length_segundos'],
      dtype='object')

In [ ]:

list(datos_completos.columns)

['ride_id',
 'rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'ride_lenght',
 'day_of_teh_week',
 'ride_leght',
 'day_of_the_week',
 'day_of_weel',
 'day_of_week',
 'ride_length',
 'ride_length_segundos']

In [ ]:
datos_completos['day_of_week'] = datos_completos['day_of_teh_week'].combine_first(datos_completos['day_of_the_week']).combine_first(datos_completos['day_of_weel'])

In [ ]:
datos_completos['day_of_week'] = datos_completos['day_of_teh_week'].combine_first(datos_completos['day_of_the_week']).combine_first(datos_completos['day_of_weel'])

In [ ]:
datos_completos['ride_length'] = datos_completos['ride_lenght'].combine_first(datos_completos['ride_leght'])

In [ ]:
datos_completos.shape

(5877002, 21)

In [ ]:
datos_completos['ride_length'].head()

0   0 days 00:15:08.087000
1   0 days 00:18:20.624000
2   0 days 00:10:58.496000
3   0 days 00:06:36.997000
4   0 days 00:11:32.497000
Name: ride_length, dtype: timedelta64[ns]

In [ ]:
datos_completos = datos_completos[datos_completos['ride_length'] >= pd.Timedelta(seconds=60)]

In [ ]:
def a_segundos(valor):
    if isinstance(valor, pd.Timedelta):
        return valor.total_seconds()
    else:
        return valor.hour * 3600 + valor.minute * 60 + valor.second + valor.microsecond / 1000000

datos_completos['ride_length_segundos'] = datos_completos['ride_length'].apply(a_segundos)

In [ ]:
import datetime

def a_segundos(valor):
    if isinstance(valor, datetime.timedelta):
        return valor.total_seconds()
    else:
        return valor.hour * 3600 + valor.minute * 60 + valor.second + valor.microsecond / 1000000

datos_completos['ride_length_segundos'] = datos_completos['ride_length'].apply(a_segundos)

In [ ]:
datos_completos = datos_completos[datos_completos['ride_length_segundos'] >= 60]

In [ ]:
datos_completos = datos_completos.drop_duplicates(subset='ride_id')

In [ ]:
datos_completos.shape

(5877002, 21)

In [ ]:
import os
ruta_csv = '/content/drive/MyDrive/Colab Notebooks/cyclistic_consolidado_limpio.csv'
print(os.path.exists(ruta_csv))
if os.path.exists(ruta_csv):
    print(f"Tamaño: {os.path.getsize(ruta_csv) / 1e6:.1f} MB")

True
Tamaño: 301.4 MB

In [ ]:
datos = pd.read_csv(ruta_csv)
print(datos.shape)

/tmp/ipykernel_9343/3801499493.py:1: DtypeWarning: Columns (13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  datos = pd.read_csv(ruta_csv)

(1209294, 21)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

datos = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cyclistic_consolidado_limpio.csv')
datos.shape

/tmp/ipykernel_9343/761036656.py:3: DtypeWarning: Columns (13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  datos = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cyclistic_consolidado_limpio.csv')

(1209294, 21)

In [ ]:

datos.groupby('member_casual')['ride_length_segundos'].mean()

member_casual
casual    1424.487470
member     787.089534
Name: ride_length_segundos, dtype: float64

In [ ]:
datos.pivot_table(index='day_of_week', columns='member_casual', values='ride_length_segundos', aggfunc='mean')

member_casual       casual      member
day_of_week
1.0            1625.356139  879.406516
2.0            1392.657168  747.297798
3.0            1209.999568  744.083895
4.0            1216.215880  759.398337
5.0            1301.893764  771.936771
6.0            1384.742238  768.842113
7.0            1553.484361  858.064742

In [ ]:
datos.pivot_table(index='day_of_week', columns='member_casual', values='ride_id', aggfunc='count')

member_casual  casual  member
day_of_week
1.0             91728   91539
2.0             51128   99313
3.0             47690  111399
4.0             49373  108502
5.0             54310  108822
6.0             77164  114920
7.0            104181   99225

In [ ]:
datos.pivot_table(index='rideable_type', columns='member_casual', values='ride_id', aggfunc='count')

member_casual  casual  member
rideable_type
classic_bike   170901  272386
electric_bike  304673  461334

In [ ]:
datos['started_at'].dtype

dtype('O')

In [ ]:
datos['started_at'] = pd.to_datetime(datos['started_at'])

In [ ]:
datos['started_at'] = pd.to_datetime(datos['started_at'], format='mixed')

In [ ]:
datos['mes'] = datos['started_at'].dt.month

In [ ]:
datos.pivot_table(index='mes', columns='member_casual', values='ride_id', aggfunc='count')

member_casual  casual  member
mes
7                  88      40
8              324081  443203
9              151405  290477

In [ ]:
datos['started_at'] = pd.to_datetime(datos['started_at'], format='mixed', dayfirst=False)
datos['mes'] = datos['started_at'].dt.month

In [ ]:
datos.pivot_table(index='mes', columns='member_casual', values='ride_id', aggfunc='count')

member_casual  casual  member
mes
7                  88      40
8              324081  443203
9              151405  290477

In [ ]:
datos[datos['ride_id'] == '21025F24DBEF6519'][['started_at', 'mes']]

Empty DataFrame
Columns: [started_at, mes]
Index: []

In [ ]:
datos[['started_at', 'mes']].sample(10)

                     started_at  mes
716460  2025-08-31 15:30:37.755    8
935164  2025-09-09 17:05:20.786    9
885706  2025-09-06 23:16:32.708    9
821615  2025-09-25 21:09:28.794    9
193259  2025-08-16 14:42:44.017    8
1112898 2025-09-26 16:33:22.588    9
994543  2025-09-14 17:17:58.844    9
1170667 2025-09-06 17:56:06.826    9
1157260 2025-09-13 09:55:15.787    9
320747  2025-08-22 13:22:02.034    8

In [ ]:
datos['started_at'].isna().sum()

np.int64(0)

In [ ]:
ruta_csv = '/content/drive/MyDrive/Colab Notebooks/cyclistic_consolidado_limpio.csv'
datos = pd.read_csv(ruta_csv)
print(datos.shape)
print(datos.columns.tolist())

/tmp/ipykernel_9343/3416411762.py:2: DtypeWarning: Columns (13,15) have mixed types. Specify dtype option on import or set low_memory=False.
  datos = pd.read_csv(ruta_csv)

(1209294, 21)
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'ride_lenght', 'day_of_teh_week', 'ride_leght', 'day_of_the_week', 'day_of_weel', 'day_of_week', 'ride_length', 'ride_length_segundos']

In [ ]:
list(datos.columns)

['ride_id',
 'rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'ride_lenght',
 'day_of_teh_week',
 'ride_leght',
 'day_of_the_week',
 'day_of_weel',
 'day_of_week',
 'ride_length',
 'ride_length_segundos']

In [ ]:
list(datos.columns)

['ride_id',
 'rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'ride_lenght',
 'day_of_teh_week',
 'ride_leght',
 'day_of_the_week',
 'day_of_weel',
 'day_of_week',
 'ride_length',
 'ride_length_segundos']

In [ ]:
datos = datos.drop(columns=['ride_lenght', 'day_of_teh_week', 'ride_leght', 'day_of_the_week', 'day_of_weel'])

In [ ]:
datos.shape

(1209294, 16)

In [ ]:
datos['started_at'] = pd.to_datetime(datos['started_at'], format='mixed', dayfirst=False)
datos['mes'] = datos['started_at'].dt.month

datos.pivot_table(index='mes', columns='member_casual', values='ride_id', aggfunc='count')

member_casual  casual  member
mes
7                  88      40
8              324081  443203
9              151405  290477

In [ ]:
# 1. Corregir ended_at igual que started_at
datos['ended_at'] = pd.to_datetime(datos['ended_at'], format='mixed', dayfirst=False)

# 2. Recalcular duración del viaje (en minutos)
datos['duracion_min'] = (datos['ended_at'] - datos['started_at']).dt.total_seconds() / 60

# 3. Revisar si hay duraciones imposibles (negativas o absurdamente largas)
print(datos['duracion_min'].describe())
print("Viajes con duración negativa:", (datos['duracion_min'] < 0).sum())
print("Viajes de más de 24 horas:", (datos['duracion_min'] > 1440).sum())

# 4. Recalcular día de la semana (si lo usabas en el análisis)
datos['dia_semana'] = datos['started_at'].dt.day_name()

count    1.209294e+06
mean     1.729594e+01
std      5.000483e+01
min      1.000050e+00
25%      6.265554e+00
50%      1.065194e+01
75%      1.847361e+01
max      1.499976e+03
Name: duracion_min, dtype: float64
Viajes con duración negativa: 0
Viajes de más de 24 horas: 970

In [ ]:
antes = datos.shape[0]

datos = datos[(datos['duracion_min'] >= 1) & (datos['duracion_min'] <= 1440)]

despues = datos.shape[0]
print(f"Filas antes: {antes}")
print(f"Filas después: {despues}")
print(f"Filas eliminadas: {antes - despues} ({(antes-despues)/antes*100:.3f}%)")

datos['duracion_min'].describe()

Filas antes: 1209294
Filas después: 1208324
Filas eliminadas: 970 (0.080%)

count    1.208324e+06
mean     1.610634e+01
std      2.717007e+01
min      1.000050e+00
25%      6.262317e+00
50%      1.064382e+01
75%      1.844582e+01
max      1.438657e+03
Name: duracion_min, dtype: float64

In [ ]:
# Confirmar que la limpieza no distorsionó la distribución mensual
datos.pivot_table(index='mes', columns='member_casual', values='ride_id', aggfunc='count')

# Confirmar tipos de datos correctos
print(datos.dtypes[['started_at', 'ended_at', 'mes', 'duracion_min', 'dia_semana']])

# Confirmar que no quedan nulos en las columnas clave
print(datos[['started_at', 'ended_at', 'duracion_min']].isnull().sum())

started_at      datetime64[ns]
ended_at        datetime64[ns]
mes                      int32
duracion_min           float64
dia_semana              object
dtype: object
started_at      0
ended_at        0
duracion_min    0
dtype: int64

In [ ]:
# Duración promedio de viaje por mes y tipo de usuario
datos.groupby(['mes', 'member_casual'])['duracion_min'].mean().unstack()

# Viajes por día de la semana
datos['dia_semana'].value_counts()

dia_semana
Saturday     203201
Friday       191918
Sunday       183067
Thursday     163005
Tuesday      159009
Wednesday    157781
Monday       150343
Name: count, dtype: int64

In [ ]:
datos.groupby(['mes', 'member_casual'])['duracion_min'].mean().unstack()

member_casual      casual     member
mes
7              171.325790  61.994650
8               21.700026  13.078143
9               19.696177  12.589401

In [ ]:
# Confirmar nombres de columnas de estación
print(datos.columns.tolist())

['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'day_of_week', 'ride_length', 'ride_length_segundos', 'mes', 'duracion_min', 'dia_semana']

In [ ]:
# Comparar si las columnas viejas coinciden con las nuevas corregidas
print((datos['ride_length'].round(2) != datos['duracion_min'].round(2)).sum())
print(datos[['day_of_week', 'dia_semana']].drop_duplicates().head(10))

1208324
     day_of_week dia_semana
0            5.0   Thursday
1            4.0  Wednesday
68           2.0     Monday
69           3.0    Tuesday
123          6.0     Friday
237          7.0   Saturday
400          1.0     Sunday

In [ ]:
datos = datos.drop(columns=['ride_length', 'day_of_week'])
print(datos.shape)
print(datos.columns.tolist())

(1208324, 17)
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'ride_length_segundos', 'mes', 'duracion_min', 'dia_semana']

In [ ]:
# Nulos en columnas de estación
print(datos[['start_station_name', 'end_station_name']].isnull().sum())
print(datos[['start_station_name', 'end_station_name']].isnull().sum() / len(datos) * 100)

# ¿Los nulos se concentran en algún tipo de bici?
print(datos[datos['start_station_name'].isnull()]['rideable_type'].value_counts())

start_station_name    251308
end_station_name      236382
dtype: int64
start_station_name    20.798064
end_station_name      19.562799
dtype: float64
rideable_type
electric_bike    251308
Name: count, dtype: int64

In [ ]:
# Top 10 estaciones de inicio (excluyendo nulos)
top_inicio = datos['start_station_name'].value_counts().head(10)
print(top_inicio)

# Top 10 estaciones de fin
top_fin = datos['end_station_name'].value_counts().head(10)
print(top_fin)

# Comparar uso de estación por tipo de usuario
datos.groupby('member_casual')['start_station_name'].apply(lambda x: x.notnull().mean())

start_station_name
Navy Pier                             18915
DuSable Lake Shore Dr & North Blvd    10778
DuSable Lake Shore Dr & Monroe St      9822
Michigan Ave & Oak St                  9325
Kingsbury St & Kinzie St               8638
Theater on the Lake                    8405
Wells St & Concord Ln                  6892
Millennium Park                        6603
Clark St & Elm St                      6550
Wells St & Elm St                      6167
Name: count, dtype: int64
end_station_name
Navy Pier                             14233
DuSable Lake Shore Dr & Monroe St     12250
Michigan Ave & Oak St                 11192
Kingsbury St & Kinzie St               9473
Clark St & Elm St                      8034
Wells St & Concord Ln                  7646
DuSable Lake Shore Dr & North Blvd     7382
Clark St & Lincoln Ave                 6862
Clinton St & Madison St                6670
Clinton St & Washington Blvd           6634
Name: count, dtype: int64

member_casual
casual    0.810285
member    0.780199
Name: start_station_name, dtype: float64

In [ ]:
print(datos['rideable_type'].value_counts())
print(datos['rideable_type'].value_counts(normalize=True) * 100)

pd.crosstab(datos['rideable_type'], datos['member_casual'], normalize='columns') * 100

datos.groupby('rideable_type')['duracion_min'].mean()

rideable_type
electric_bike    766007
classic_bike     442317
Name: count, dtype: int64
rideable_type
electric_bike    63.394172
classic_bike     36.605828
Name: proportion, dtype: float64

rideable_type
classic_bike     20.093193
electric_bike    13.804202
Name: duracion_min, dtype: float64

In [ ]:
!pip install python-calamine --quiet

ruta = '/content/drive/MyDrive/Colab Notebooks/'
tablas = []

for archivo in archivos:
    print(f"Leyendo {archivo}...")
    tabla = pd.read_excel(ruta + archivo, engine='calamine')
    tablas.append(tabla)

datos_completos = pd.concat(tablas, ignore_index=True)
print("Listo:", datos_completos.shape)

Leyendo 202508-divvy-tripdata.xlsx...
Leyendo 202509-divvy-tripdata.xlsx...
Leyendo 202510-divvy-tripdata.xlsx...
Leyendo 202511-divvy-tripdata.xlsx...
Leyendo 202512-divvy-tripdata.xlsx...
Leyendo 202601-divvy-tripdata.xlsx...
Leyendo 202602-divvy-tripdata.xlsx...
Leyendo 202603-divvy-tripdata.xlsx...
Leyendo 202604-divvy-tripdata.xlsx...
Leyendo 202605-divvy-tripdata.xlsx...
Leyendo 202606-divvy-tripdata.xlsx...
Leyendo 202607-divvy-tripdata.xlsx...
Listo: (6037968, 19)

In [ ]:
print(datos.shape)
print(datos.columns.tolist())
print(datos.dtypes[['started_at', 'ended_at']] if 'started_at' in datos.columns else "no existe started_at")

(1208324, 17)
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'ride_length_segundos', 'mes', 'duracion_min', 'dia_semana']
started_at    datetime64[ns]
ended_at      datetime64[ns]
dtype: object

In [ ]:
# Filas por mes en el consolidado actual
print(datos.groupby('mes').size().sort_index())

# Total de filas
print("Total:", len(datos))

# ¿Hay algún mes con muy pocas filas comparado a los demás? (señal de carga incompleta)

mes
7        99
8    766591
9    441634
dtype: int64
Total: 1208324

In [ ]:
!pip install python-calamine --quiet

In [ ]:
import pandas as pd

archivos = ['202508-divvy-tripdata.xlsx', '202509-divvy-tripdata.xlsx', '202510-divvy-tripdata.xlsx',
            '202511-divvy-tripdata.xlsx', '202512-divvy-tripdata.xlsx', '202601-divvy-tripdata.xlsx',
            '202602-divvy-tripdata.xlsx', '202603-divvy-tripdata.xlsx', '202604-divvy-tripdata.xlsx',
            '202605-divvy-tripdata.xlsx', '202606-divvy-tripdata.xlsx', '202607-divvy-tripdata.xlsx']

ruta = '/content/drive/MyDrive/Colab Notebooks/'
tablas = []

for archivo in archivos:
    print(f"Leyendo {archivo}...")
    tabla = pd.read_excel(ruta + archivo, engine='calamine')
    print(f"  → {tabla.shape[0]} filas")
    tablas.append(tabla)

datos = pd.concat(tablas, ignore_index=True)
print("TOTAL:", datos.shape)

Leyendo 202508-divvy-tripdata.xlsx...
  → 790177 filas
Leyendo 202509-divvy-tripdata.xlsx...
  → 714759 filas
Leyendo 202510-divvy-tripdata.xlsx...
  → 646039 filas
Leyendo 202511-divvy-tripdata.xlsx...
  → 356628 filas
Leyendo 202512-divvy-tripdata.xlsx...
  → 140534 filas
Leyendo 202601-divvy-tripdata.xlsx...
  → 137787 filas
Leyendo 202602-divvy-tripdata.xlsx...
  → 201450 filas
Leyendo 202603-divvy-tripdata.xlsx...
  → 317037 filas
Leyendo 202604-divvy-tripdata.xlsx...
  → 448252 filas
Leyendo 202605-divvy-tripdata.xlsx...
  → 653704 filas
Leyendo 202606-divvy-tripdata.xlsx...
  → 762550 filas
Leyendo 202607-divvy-tripdata.xlsx...
  → 869051 filas
TOTAL: (6037968, 19)

In [ ]:
print(datos.columns.tolist())

['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'ride_lenght', 'day_of_teh_week', 'ride_leght', 'day_of_the_week', 'day_of_weel', 'day_of_week']

In [ ]:
datos = datos.drop(columns=['ride_lenght', 'ride_leght', 'day_of_teh_week',
                              'day_of_the_week', 'day_of_weel', 'day_of_week'])
print(datos.shape)

(6037968, 13)

In [ ]:
# 1. Corregir fechas (formato mixto)
datos['started_at'] = pd.to_datetime(datos['started_at'], format='mixed', dayfirst=False)
datos['ended_at'] = pd.to_datetime(datos['ended_at'], format='mixed', dayfirst=False)

# 2. Columnas derivadas
datos['mes'] = datos['started_at'].dt.month
datos['duracion_min'] = (datos['ended_at'] - datos['started_at']).dt.total_seconds() / 60
datos['dia_semana'] = datos['started_at'].dt.day_name()

# 3. Filtrar duraciones imposibles (<1 min o >24h)
antes = datos.shape[0]
datos = datos[(datos['duracion_min'] >= 1) & (datos['duracion_min'] <= 1440)]
print(f"Filas eliminadas: {antes - datos.shape[0]}")

# 4. Verificación
print(datos.shape)
print(datos.groupby('mes').size().sort_index())

Filas eliminadas: 166272
(5871696, 16)
mes
1     133743
2     197317
3     308466
4     435506
5     635395
6     741382
7     845967
8     766663
9     695681
10    628474
11    346643
12    136459
dtype: int64

In [ ]:
datos.to_csv('/content/drive/MyDrive/Colab Notebooks/cyclistic_consolidado_limpio.csv', index=False)
print("Guardado.")

Guardado.

In [ ]:
from google.colab import files
files.download('/content/drive/MyDrive/Colab Notebooks/cyclistic_consolidado_limpio.csv')

In [ ]:
print(datos.isnull().sum())

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1180581
start_station_id      1180581
end_station_name      1219261
end_station_id        1219261
start_lat                   0
start_lng                   0
end_lat                   278
end_lng                   278
member_casual               0
mes                         0
duracion_min                0
dia_semana                  0
dtype: int64

In [ ]:
pd.crosstab(datos['rideable_type'], datos['member_casual'], normalize='columns') * 100

member_casual     casual     member
rideable_type
classic_bike   29.386374  33.604448
electric_bike  70.613626  66.395552

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
datos = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cyclistic_consolidado_limpio.csv')
print(datos.shape)

Mounted at /content/drive
(5871696, 16)

In [ ]:
resumen_mes = datos.pivot_table(index='mes', columns='member_casual', values='ride_id', aggfunc='count')
resumen_dia = datos['dia_semana'].value_counts()
resumen_duracion_mes = datos.groupby(['mes', 'member_casual'])['duracion_min'].mean().unstack()
top_inicio = datos['start_station_name'].value_counts().head(10)
top_fin = datos['end_station_name'].value_counts().head(10)
resumen_bici = datos['rideable_type'].value_counts()
crosstab_bici = pd.crosstab(datos['rideable_type'], datos['member_casual'], normalize='columns') * 100
duracion_bici = datos.groupby('rideable_type')['duracion_min'].mean()

ruta = '/content/drive/MyDrive/Colab Notebooks/resumenes_cyclistic.xlsx'
with pd.ExcelWriter(ruta) as writer:
    resumen_mes.to_excel(writer, sheet_name='viajes_por_mes')
    resumen_dia.to_excel(writer, sheet_name='viajes_por_dia')
    resumen_duracion_mes.to_excel(writer, sheet_name='duracion_por_mes')
    top_inicio.to_excel(writer, sheet_name='top_estaciones_inicio')
    top_fin.to_excel(writer, sheet_name='top_estaciones_fin')
    resumen_bici.to_excel(writer, sheet_name='tipo_bici')
    crosstab_bici.to_excel(writer, sheet_name='tipo_bici_por_usuario')
    duracion_bici.to_excel(writer, sheet_name='duracion_por_tipo_bici')

print("Guardado en:", ruta)

Guardado en: /content/drive/MyDrive/Colab Notebooks/resumenes_cyclistic.xlsx